[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5"
itertools = "0.13.0"
memoize = "0.4.2"
num = "*"
regex = "1.11.1"

